baseURL = "https://rudeigerc.dev/"
languageCode = "zh-Hans"
title = "Luthadel"
theme = "yggdrasill"
copyright = "© 2022 Yuchen Cheng. This site is licensed under a Creative Commons Attribution 4.0 International license."

disqusShortname = "rudeigerc"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
googleAnalytics = "G-HXB6L4QSKP"
hasCJKLanguage = true
paginate = 5
# pygmentsCodefencesGuessSyntax = true
# pygmentsCodeFences = true
# pygmentsUseClasses = true


[author]
  name = "Yuchen Cheng"
  email = "rudeigerc@gmail.com"

[menu]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "Catagories"
  url = "/categories"
  weight = 3

[[menu.main]]
  name = "Series"
  url = "/series"
  weight = 4

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 5

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 6

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]
  [markup.highlight]
    style = "github"

[params]
  subtitle = "Yuchen Cheng's Blog"
  description = "Yuchen Cheng's Blog"

  [params.giscus]
    dataRepo = "rudeigerc/rudeigerc.github.io"
    dataRepoID = "MDEwOlJlcG9zaXRvcnkxMDcxNDQ2MTg="
    dataCategory = "Comments"
    dataCategoryID = "DIC_kwDOBmLlqs4CPSgG"

[[params.social]]
  name = "GitHub"
  url = "https://github.com/rudeigerc"
  type = "fab"
  icon = "github"

[[params.social]]
  name = "Twitter"
  url = "https://twitter.com/yuchen_cheng"
  type = "fab"
  icon = "twitter"

[[params.social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/rudeigerc/"
  type = "fab"
  icon = "linkedin"

[[params.social]]
  name = "E-mail"
  url = "mailto:rudeigerc@gmail.com"
  type = "fas"
  icon = "envelope"

[[params.social]]
  name = "Resume"
  url = "/files/resume.pdf"
  type = "fas"
  icon = "file"

[[params.social]]
  name = "RSS"
  url = "/index.xml"
  type = "fas"
  icon = "rss"
